Make region fetching async - fix ENOBUFS error on syncRequest  (#549)
### Background

When running `npm run fullBuild`, the build would sometimes fail when attempting to fetch AWS regions with the following error:

```
> ts-node ./build-scripts/generateResources.ts
Fetching AWS regions
Error: spawnSync /usr/local/bin/node ENOBUFS
```
### Problem
The reason for this error is due to our use of the synchronous `syncRequest` for making the HTTP fetch request.

### Solution
Make region fetching async using `axios.get`